apiVersion: v1
kind: Secret
metadata:
  name: smartem-secrets
  namespace: smartem-decisions
type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWU=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  RABBITMQ_USER: dXNlcm5hbWU=
  RABBITMQ_PASSWORD: cGFzc3dvcmQ=
